### PR TITLE
Feature/std crypto

### PR DESCRIPTION
**Pull request by Apprentice-Alchemist**

### CODE REVIEW

**Comment by flashultra** [comment]
What is the main idea here ? 
Remove these files from the Haxe std repository or have them on both places?

**Comment by Simn** [comment]
They'll be removed from std once we have them here and taught haxelib to use them.

**Comment by flashultra** [comment]
My thoughts, about this PR:
 1) Moving Base64 and BaseCode outside Haxe std will "cripple" Haxe as a language. These are core methods that  have a foundational functionality and are widely used.If I want to use them, I won't want to install another library (which is the npm approach). Also, there are not a cryptophraphic functionality in them.  So I am more negative about removing them.
 2) Adler32 and Crc32 are checksum algorithms. They are not that widely used and may have a place here, althougth there are not crypto functions.
The other changes looks ok.

**Comment by Simn** [comment]
Base64 is actually used by other parts of the standard library, so it should stay there. Maybe we can move it to a different package though because "crypto" is really weird. I'm not sure about BaseCode, will have to check.

I think moving checksum algorithms here is fine. You're right that they are not crypto functions strictly speaking, but I'd like to be pragmatic about this.

**Comment by Apprentice-Alchemist** [comment]
Right, I forgot that base64 was used in haxe.Resource (on JS and Lua).
I also agree that having it in `haxe.crypto` is weird.
BaseCode is currently used for the implementation of Base64.

**Comment by flashultra** [comment]
About moving Base64 and BaseCode , here some suggestions for package names: 
```haxe.encoding.```, ```haxe.encode.``` , ```haxe.util.encoding``` , ```haxe.util.encode```, ```haxe.codec``` ( so it will be ```haxe.encoding.Base64```, ```haxe.encode.Base64 ``` ,  etc. )

About Adler32 and Crc32 , they could be in the main crypto folder or in other package with name, such as : 
- ```haxe.util.checksum``` for Adler32 (since it is checksum algorithm) or ```haxe.misc.checksum```
-  ```haxe.util.crc``` for Crc32 ( since it is  CRC ) or ```haxe.misc.crc```, ```haxe.io,crc```
- ```haxe.crypto``` - main package

Both algorithms (Adler32, Crc32) can be extended by adding crc8, crc16,, crc64 (for CRC) and  fletcher-32,Luhn algorithm, etc ( for checksum / Adler32). 
I'm still not sure which is the best place for the two files (Adler32/Crc32)

**Comment by Simn** [comment]
Let's go with `haxe.crypto` for now, I'm not really keen on creating a new package for this.

**Comment by flashultra** [comment]
Maybe tests for MD5, Sha1, Adler32, Crc32, etc. should be added here ?

**Pull request merged**
